pre-commit:
  parallel: true
  jobs:
    - name: Format
      run: npm run format

    - name: Lint
      run: npm run lint

    - name: Typecheck
      run: npm run typecheck

commit-msg:
  commands:
    commitlint:
      run: npx commitlint --edit {1}
