export enum Service {
  IDENTITY = 'IDENTITY',
  BILLIARD_TABLES = 'BILLIARD_TABLES',
  BOOKING = 'BOOKING',
  TOURNAMENTS = 'TOURNAMENTS',
  STATISTICS = 'STATISTICS',
  NEWS = 'NEWS',
  NOTIFICATION = 'NOTIFICATION',
  STORAGE = 'STORAGE',
}
