export const BOOKING_DAYS_AHEAD = 7;
export const BOOKING_SLOT_STEP_MINUTES = 15;
export const BOOKING_WORK_START_HOUR = 9;
export const BOOKING_WORK_START_MINUTES = BOOKING_WORK_START_HOUR * 60;
export const BOOKING_WORK_END_MINUTES = 24 * 60;
export const BOOKING_MIN_DURATION_MINUTES = 30;
export const BOOKING_MAX_DURATION_HOURS = 5;
export const BOOKING_MAX_DURATION_MINUTES = BOOKING_MAX_DURATION_HOURS * 60;

export const BUSINESS_TIMEZONE_OFFSET_HOURS = 3;
export const HOUR_IN_MS = 1000 * 60 * 60;
export const MINUTE_IN_MS = 1000 * 60;
